# Generated by Django 5.1 on 2025-11-24 12:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='images', verbose_name='Logo')),
                ('site_name', models.CharField(default='Baku Times', max_length=255)),
                ('title', models.CharField(default='Xəbərlər və Məqalələr Saytı', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('maintenance_mode', models.CharField(default='light', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Şəkil'),
        ),
    ]
